name: Trigger auto deployment for astro-ssr-docker

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/astro-ssr-docker-AutoDeployTrigger-fec93b01-cbcb-4210-8a99-a3788677b747.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ASTROSSRDOCKER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ASTROSSRDOCKER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ASTROSSRDOCKER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.ASTROSSRDOCKER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ASTROSSRDOCKER_REGISTRY_PASSWORD }}
          containerAppName: astro-ssr-docker
          resourceGroup: next-docker
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


